image:
  file: .gitpod.dockerfile
tasks:
  - before: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
    command: /home/gitpod/.pg_ctl/bin/pg_start > /dev/null
  - command: . ${GITPOD_REPO_ROOT}/.vscode/uptime.sh &
  - name: Start server
    command: |
      pip install -r requirements.txt
      find . -name '*.pyc' -type f | xargs rm -f
      python manage.py migrate
      python manage.py runserver
      
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - eventyret.bootstrap-4-cdn-snippet
    - hookyqr.beautify
    - matt-rudge.auto-open-preview-panel
    - ms-toolsai.jupyter
