# Generated by Django 3.2.9 on 2021-12-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_rating',
            new_name='rating',
        ),
    ]
