# Generated by Django 3.2.9 on 2021-12-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_product_rating_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_option',
        ),
    ]
