# Generated by Django 3.2.9 on 2021-12-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_product_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('XXS', 'XXSmall'), ('XS', 'XSmall'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'XLarge'), ('XXL', 'XXLarge')], default='S', max_length=7),
        ),
    ]
