# Generated by Django 3.2.9 on 2021-12-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211220_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.CharField(choices=[('XXSmall', 'XXS'), ('XSmall', 'XS'), ('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('XLarge', 'XL'), ('XXLarge', 'XXL')], default='S', max_length=7),
        ),
    ]
