# Generated by Django 3.2.9 on 2022-01-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_sale',
            new_name='sale_percentage',
        ),
        migrations.AddField(
            model_name='product',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
