# Generated by Django 3.2.9 on 2022-01-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220115_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_add_rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
