# Generated by Django 3.2.9 on 2022-01-19 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_product_productreview_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='products',
            new_name='product',
        ),
    ]
